### ISSUE TITLE
Define user roles in gate

### ISSUE THREAD

**Issue by olttwa** [gate-sso/gate#31]
I as an admin, want to create user categories and admin roles for users so that admins can manage their respective user groups and their access to integration/production environment as required. 

Acceptance Criteria : 

- Users should be classified into 4 categories - Super Admin, Group Admin, IT Admin and Users
- Every user with a valid and approved  google account is a user by default
- Super Admin privileges will rest with Systems team
- IT Admin and Group Admin privileges will need to be enabled by super admin.

**Comment by ajeygore** [comment]
As an admin user
I should be able to create user groups 
so that I can assign users to specific groups with privileges as per following detailed criteria

1. there will be four group types - Super Admin (Can modify everything), Group Admin (Can add and remove users from the group), IT Admin (Should be able see everything and add and remove users to various groups), Host Groups (should be able to add and remove hosts

2. Super admin can modify any user and assign them to any groups

**Acceptance Criteria**

1. As a super admin I should be able to make any user group admin, IT admin for any Group.
2. As a group admin I should be able to add users to only my listed group.
3. We should be able to do these operations with API with Access Tokens

**Comment by ajeygore** [comment]
Changing logic a bit. We are adding only one more role - IT Admin (which can see everything, but Admin will be able to see everything and modify)

apart from that, we should have group admins for a group in a group. :-)

Complex, but we should try to drive everything using group now.

**Comment by ajeygore** [comment]
Now, there are only two roles group admin and super admin, no one should have any other role, we are closing this, unless you think we need to do better.
