### ISSUE TITLE
Provide filter for group lists

### ISSUE THREAD

**Issue by ajeygore** [gate-sso/gate#82]
All group list should provide filter for Only active users and not inactive users, also, prune all inactive members from all the groups.

**Comment by giosakti** [comment]
I'll work on this

**Comment by ajeygore** [comment]
Thanks :-)

**Comment by giosakti** [comment]
- [] don't show active users on users autocomplete
- [] prune all inactive members from all the groups (?) 

for pruning, do you mean a button for admin that query and remove all inactive members on all groups, or should it be a periodic worker?

**Comment by ajeygore** [comment]
There should be button for now, later - when we deactivate a user, he should be removed from all groups if he is deactivated for 15 days.

So that accidental deactivation does not matter.

Ajey

**Comment by giosakti** [comment]
ok, I'll create that functionality & button that remove all inactive members from all groups.

As for the second scenario `when we deactivate a user, he should be removed from all groups if he is deactivated for 15 days.`.

I will create a rake task and create a job using `whenever` to call that rake task every midnight. Thus in every gate deployment we should run `whenever --update-crontab` so that the job is added to the server's cronjobs.

**Comment by ajeygore** [comment]
@giosakti is this done?

**Comment by ajeygore** [comment]
I think we should provide Include inactive user as a checkbox on UI to close it.

**Comment by giosakti** [comment]
sure, will add that

**Comment by ajeygore** [comment]
Can we close this issue?

**Comment by giosakti** [comment]
@ajeygore 
Please check #121 to solve `Include inactive user as a checkbox on UI`
if that is merged, we can close this

**Comment by ajeygore** [comment]
Done with merge, will wait for build and then we should deploy today or tomorrow.
