### ISSUE TITLE
Assign users to group via API

### ISSUE THREAD

**Issue by giosakti** [gate-sso/gate#89]
- As developer of external service which utilizes gate
- I want to be able to assign users in my service to a group in gate
- Gate should provide API for assigning and removing users from a group

@ajeygore, There are some services depends on Gate API to assign/remove user from group. It used to exist on `nss_controller#add_user_to_group`. 

How can these external services do it now? should I create a new API?

**Comment by ajeygore** [comment]
Which services are those? They are using old auth token, So they need to use API token to do something. add_user_to_group shouldn't be used anymore, instead those service admins should be made group admins of those groups and they should come to gate and then manipulate, I don't think that services are doing that automatically. That's why I removed that from the nss_controller.

**Comment by giosakti** [comment]
From what I understand, this service is operation portal (customer service and stuff)

it seems that their admins are not using gate ui at all, and the apps communicate behind the scene with gate to add user to groups using that API on nss_controller.

**Comment by giosakti** [comment]
Okay, I shall discuss with them tomorrow about this

**Comment by giosakti** [comment]
This issue has been communicated and the affected service will use gate user interface instead to add users to group.
